# NumPy

NumPy is a Linear Algebra library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is incredibly fast, as it has bindings to C libraries.


__Installation Direction - Type the following in Command Shell__

_conda install numpy_

## NumPy Arrays

Numpy arrays essentially come in two type — 

-  Vectors
-  Matrices

Vectors are one dimensional arrays and matrices are two dimensional (Matrices can have only one row and column as well).

In [1]:
list = [1,2,3]

In [2]:
list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3])

In [6]:
new_mat = [[1,2,3],[3,4,5],[5,6,7]]

In [7]:
np.array(new_mat)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [8]:
np.arange(0,10) #useful for quickly creating new arrays

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,6)) #pass a tuple to create a matrix of the required dimensions

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10) #Don't confuse linspace with range

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [22]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5) #numbers uniformly distributed from 0 to 1

array([0.24250522, 0.7729702 , 0.88664935, 0.54021079, 0.56981632])

In [24]:
np.random.rand(5,5) #creates a matrix as you can notice the  double brackets

array([[0.18633351, 0.13202907, 0.67094571, 0.37627372, 0.91127927],
       [0.83437204, 0.39639056, 0.72458809, 0.33425718, 0.17604823],
       [0.96476706, 0.77630865, 0.14120188, 0.11025213, 0.19718676],
       [0.48562829, 0.20392427, 0.85807992, 0.62472831, 0.62707908],
       [0.52668533, 0.1790824 , 0.33269676, 0.6256273 , 0.54340668]])

In [25]:
np.random.randn(2)

array([2.18265194, 0.71880103])

In [26]:
np.random.rand(5,4)

array([[0.60092205, 0.05843362, 0.67332096, 0.77590846],
       [0.46850416, 0.30023894, 0.20959692, 0.12330434],
       [0.92393229, 0.72038977, 0.87034166, 0.05051723],
       [0.97142571, 0.69016426, 0.82166014, 0.19023802],
       [0.54557724, 0.86179599, 0.43131094, 0.31441531]])

In [27]:
np.random.randint(1,100)

9

In [28]:
np.random.randint(1,100,10)

array([96, 34, 53, 90, 52, 57, 66, 38,  7, 24])

In [30]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
ranarr = np.random.randint(0,50,10)
ranarr

array([43, 26,  2,  4,  5, 38, 26, 27, 15,  6])

In [35]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
ranarr

array([43, 26,  2,  4,  5, 38, 26, 27, 15,  6])

In [38]:
ranarr.max()

43

In [39]:
ranarr.min()

2

In [40]:
ranarr.argmax()

0

In [41]:
ranarr.argmin()

2

In [42]:
arr = arr.reshape(5,4) #reshaping the array into a matrix

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [44]:
arr.dtype #checking the datatype of the array

dtype('int32')

In [45]:
from numpy.random import randint

In [47]:
randint(2,19)

8

## NumPy Indexing and Selection

In [49]:
arr1 = np.arange(0,11)

In [51]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr1[8] #indexing is similar to strings and lists

8

In [53]:
arr1[1:5]

array([1, 2, 3, 4])

In [54]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr1[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
#numpy arrays differ from Python lists because of their ability to broadcast

arr1[0:5] = 100

In [59]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
slice_of_arr1= arr1[0:6]

In [64]:
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr1[0:6] = 99

In [66]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [67]:
arr1 #Therefore, here you can see that NumPy performs shallow copying in such cases. It does it so as to avoid memory issues in case of large arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
#To actually deep copy the array, the followimng can be done
arr1_copy = arr1.copy()

In [69]:
arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr1_copy[0:6] = 100

In [71]:
arr1_copy #Deep copy and this broadcasting does not change the original arr1

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
#Grabbing elements/selection of elements

arr_2d[0][0]

5

In [76]:
arr_2d[0]

array([ 5, 10, 15])

In [77]:
arr_2d[2][1] #row index and column index

40

In [79]:
#another way to select the element of your choice is to use the following method

arr_2d[2,1] #recommended

40

In [80]:
#Selecting certain sections of the array

arr_2d[:2,1:] #slice notation

array([[10, 15],
       [25, 30]])

### Conditional Selection

In [81]:
arr2 = np.arange(1,11)

In [82]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr = arr2 > 5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
arr2[bool_arr]

array([ 6,  7,  8,  9, 10])

In [94]:
#or

arr2[arr2<3]

array([1, 2])

In [95]:
arr_2d1 = np.arange(50).reshape(5,10)

In [96]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## NumPy Operations

-  Array with Array
-  Array with Scalar
-  Universal Array Function

In [97]:
arr3 = np.arange(0,11)

In [98]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr3 + arr3 #addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr3 - arr3 #subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr3 * arr3 #multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [104]:
arr3 **3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [105]:
arr3 + 100 #scalar addition, happens elementwise

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
1/0

ZeroDivisionError: division by zero

In [107]:
arr3 / arr3 #null, NumPy issues a warning 

C:\Users\akash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
1 / arr3 #inf, NumPy issues a warning

C:\Users\akash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [109]:
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [110]:
np.exp(arr3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [112]:
np.max(arr3)

10

In [113]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [114]:
np.log(arr3)

C:\Users\akash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# NOTE - Do check out NumPy documentation page